In [8]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


The filename, directory name, or volume label syntax is incorrect.


In [9]:
import numpy as np

Creating Numpy Arrays

In [10]:
data_1d = np.array([1,2,3,4,5])

In [11]:
data_2d = np.array([[1,2,3],[4,5,6]])

Array Shape and Dimensions

In [12]:
print(data_1d.shape)

(5,)


In [13]:
print(data_2d.shape)

(2, 3)


In [14]:
#array reshaping
reshaped_Arr = data_2d.reshape(3,2)
#print array
reshaped_Arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
print(data_2d.ndim)

2


Array Indexing and Slicing

In [17]:
data_1d

array([1, 2, 3, 4, 5])

In [16]:
#accessing elements
print(data_1d[0])

1


In [18]:
data_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
print(data_2d[1,2])

6


In [20]:
#slicing
print(data_1d[:3])

[1 2 3]


In [21]:
data_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
print(data_2d[:, 1:])

[[2 3]
 [5 6]]


Array Operations

In [23]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [24]:
addition = a+b

In [25]:
addition

array([5, 7, 9])

In [26]:
multiplication = a*b
multiplication

array([ 4, 10, 18])

In [30]:
exp_a = np.exp(a)
exp_a

array([ 2.71828183,  7.3890561 , 20.08553692])

In [31]:
log_b = np.log(b)
log_b

array([1.38629436, 1.60943791, 1.79175947])

Broadcasting

In [32]:
#broadcasting with scalar
a=np.array([1,2,3])
b=10

# 10 ----> [10,10,10]

result = a+b
result

array([11, 12, 13])

Array Aggregation

In [33]:
data = np.array([[1,2,3],[4,5,6]])

In [35]:
total_Sum = np.sum(data)
total_Sum

21

In [36]:
#column only
column_sum = np.sum(data,axis=0)
column_sum

array([5, 7, 9])

In [37]:
row_mean = np.mean(data, axis=1)
row_mean

array([2., 5.])